### ISSUE TITLE
[IDEA] FPS Settings Button

### ISSUE THREAD

**Issue by Musa-Sina-Ertugrul** [Musa-Sina-Ertugrul/QuestGame#10]
**Is your feature request related to a problem? Please describe.**

>A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

> FPS Button will have 30-60-120-144-160-240-360 settings when you click the right side of the screen you will reach higher values and on the left side that will be in the opposite direction. The button must be like the sound button. It must meet OOAD Specs.

**Describe the solution you'd like**

<details open>
<summary>A clear and concise description of what you want to happen. Write Pseudocode with Python</summary>

```python

HERE

```

</details>

**Describe alternatives you've considered**

<details open>
<summary>A clear and concise description of any alternative solutions or features you've considered. Write Pseudocode with Python</summary>

```python

HERE

```

</details>

**Additional context**

<details open>
<summary>Add any other context or screenshots about the feature request here.</summary>

>HERE

</details>

**Comment by icelal-kskn** [comment]
I can do it 🗡️
