### ISSUE TITLE
[IDEA] Change super variables to self variables

### ISSUE THREAD

**Issue by Musa-Sina-Ertugrul** [Musa-Sina-Ertugrul/QuestGame#8]
**Is your feature request related to a problem? Please describe.**

>A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

>Changing super variables to self variables will help the coding experience because when you type super you can not see parent variables but if we use self we will see them

**Describe the solution you'd like**

<details open>
<summary>A clear and concise description of what you want to happen. Write Pseudocode with Python</summary>

```python

super.external_states = [] to self.external_states = []

```

</details>

**Describe alternatives you've considered**

<details open>
<summary>A clear and concise description of any alternative solutions or features you've considered. Write Pseudocode with Python</summary>

```python

No alternatives

```

</details>

**Additional context**

<details open>
<summary>Add any other context or screenshots about the feature request here.</summary>

>HERE

</details>

**Comment by Iremmd** [comment]
I accepted.
