### ISSUE TITLE
[IDEA] Change NoReturn with None

### ISSUE THREAD

**Issue by Musa-Sina-Ertugrul** [Musa-Sina-Ertugrul/QuestGame#9]
**Is your feature request related to a problem? Please describe.**

>A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

>Changing NoReturn with None will prevent from unreachable lines

**Describe the solution you'd like**

<details open>
<summary>A clear and concise description of what you want to happen. Write Pseudocode with Python</summary>

```python

NoReturn to None

```

</details>

**Describe alternatives you've considered**

<details open>
<summary>A clear and concise description of any alternative solutions or features you've considered. Write Pseudocode with Python</summary>

```python

No alternatives

```

</details>

**Additional context**

<details open>
<summary>Add any other context or screenshots about the feature request here.</summary>

>HERE

</details>

**Comment by CengizhanBayram** [comment]
I accepted
